// ════════════════════════════════════════════
//  EMAIL OVERVIEW TAB  —  crm/email.js
// ════════════════════════════════════════════

CRM.registerTab({
  id: 'email',
  label: 'Email Overview',
  icon: '✉️',

  render(el) {
    el.innerHTML = `
      <div class="section-header">
        <span class="section-title">Email Overview</span>
        <div class="section-actions">
          <button class="btn btn-outline btn-sm" onclick="EmailTab.refresh()">↻ Refresh</button>
        </div>
      </div>

      <!-- Search / filter -->
      <div style="margin-bottom:16px;display:flex;gap:10px;">
        <input class="form-input" id="email-search" placeholder="Search subject or sender…" oninput="EmailTab.filter()" style="max-width:320px;">
        <select class="form-select" id="email-filter" onchange="EmailTab.filter()" style="max-width:160px;">
          <option value="">All</option>
          <option value="unread">Unread</option>
          <option value="starred">Starred</option>
        </select>
      </div>

      <div class="card">
        <div class="card-head">
          <span class="card-title-icon">📥</span> Inbox
          <span id="email-count" style="margin-left:6px;font-size:11px;color:var(--text-dim);font-weight:400;"></span>
        </div>
        <div class="card-body" id="email-list">
          <div class="empty-state"><div class="spinner"></div><p style="margin-top:10px;">Loading…</p></div>
        </div>
      </div>

      <!-- Thread preview panel -->
      <div id="email-thread-panel" style="display:none;margin-top:16px;">
        <div class="card">
          <div class="card-head">
            <span id="email-thread-subject" style="font-weight:600;"></span>
            <div class="card-head-actions">
              <button class="btn btn-outline btn-sm" onclick="EmailTab.closeThread()">✕ Close</button>
            </div>
          </div>
          <div class="card-body" id="email-thread-body"></div>
        </div>
      </div>`;

    EmailTab._load();
  },

  onActivate() { EmailTab._load(); }
});

window.EmailTab = (() => {
  let _all = [];

  function _load() {
    const el = document.getElementById('email-list');
    if (!el) return;

    // Try scheduled brief JSON
    fetch('./gmail-brief.json?_=' + Date.now())
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (data && data.threads) {
          _all = data.threads;
          CRM.save('email-threads', _all);
          _render(_all);
          const ct = document.getElementById('email-count');
          if (ct) ct.textContent = `${data.unread ?? _all.length} unread`;
        } else {
          _fromCache();
        }
      })
      .catch(_fromCache);
  }

  function _fromCache() {
    _all = CRM.load('email-threads', []);
    if (_all.length) {
      _render(_all);
    } else {
      const el = document.getElementById('email-list');
      if (el) el.innerHTML = `
        <div class="empty-state">
          <div class="empty-icon">🔌</div>
          <p>Connect Gmail to see your inbox here.</p>
          <p style="margin-top:6px;font-size:11px;">The app reads from <code>gmail-brief.json</code> — generated by your scheduled Claude task.</p>
        </div>`;
    }
  }

  function _render(threads) {
    const el = document.getElementById('email-list');
    if (!el) return;
    if (!threads.length) {
      el.innerHTML = `<div class="empty-state"><div class="empty-icon">✉️</div><p>No emails to show</p></div>`;
      return;
    }
    el.innerHTML = threads.map((t,i) => `
      <div class="list-row" style="cursor:pointer;${t.unread ? 'font-weight:600;' : ''}" onclick="EmailTab.openThread(${i})">
        <div class="avatar">${CRM.initials(t.from || t.sender || '?')}</div>
        <div class="list-row-main">
          <div class="list-row-title">${esc(t.subject || '(no subject)')}${t.unread ? ' <span style="width:7px;height:7px;background:var(--accent);border-radius:50%;display:inline-block;margin-left:5px;vertical-align:middle;"></span>' : ''}</div>
          <div class="list-row-sub">${esc(t.from || t.sender || '')}${t.snippet ? ' — ' + esc(t.snippet.slice(0,80)) : ''}</div>
        </div>
        <div class="list-row-meta">${t.date ? CRM.fmtDate(t.date) : ''}</div>
      </div>`).join('');
  }

  function filter() {
    const q = (document.getElementById('email-search')?.value || '').toLowerCase();
    const f = document.getElementById('email-filter')?.value || '';
    let filtered = _all;
    if (q) filtered = filtered.filter(t =>
      (t.subject||'').toLowerCase().includes(q) ||
      (t.from||t.sender||'').toLowerCase().includes(q));
    if (f === 'unread') filtered = filtered.filter(t => t.unread);
    if (f === 'starred') filtered = filtered.filter(t => t.starred);
    _render(filtered);
  }

  function refresh() { _load(); }

  function openThread(idx) {
    const t = _all[idx];
    if (!t) return;
    const panel = document.getElementById('email-thread-panel');
    const subj  = document.getElementById('email-thread-subject');
    const body  = document.getElementById('email-thread-body');
    if (!panel || !subj || !body) return;

    subj.textContent = t.subject || '(no subject)';
    body.innerHTML = `
      <div style="margin-bottom:10px;">
        <strong>From:</strong> ${esc(t.from || t.sender || '—')}<br>
        <strong>Date:</strong> ${t.date ? CRM.fmtDate(t.date) : '—'}
      </div>
      <div style="white-space:pre-wrap;font-size:13px;line-height:1.6;color:var(--text);">
        ${esc(t.body || t.snippet || 'No content available.')}
      </div>`;
    panel.style.display = 'block';
    panel.scrollIntoView({ behavior: 'smooth' });
  }

  function closeThread() {
    const panel = document.getElementById('email-thread-panel');
    if (panel) panel.style.display = 'none';
  }

  function esc(s) {
    return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  }

  return { _load, refresh, filter, openThread, closeThread };
})();
